http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  app:
    host: localhost
    path: ["/", "/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  appService:
    urls:
      - http://localhost:3001
      - http://localhost:3002
      - http://localhost:3003
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - app
    policies:
      - proxy:
          - action:
              serviceEndpoint: appService
              changeOrigin: true
